### ISSUE TITLE
Possible to use over displayport?

### ISSUE THREAD

**Issue by whalesalad** [nikosdion/asdcontrol#5]
I am using a displayport->usb cable in order to use my display on Debian 12. Do you know if this would be possible to use with this software? I am unable to see anything with the detect command, likely because my display is not on the usb bus:

```
 sudo ./asdcontrol --detect /dev/usb/hiddev*
ASDControl 0.4 -- Apple Studio Display Brightness Control
Copyright (c) 2023-2024 Nicholas K. Dionysopoulos

hiddev driver version is 1.0.4
hiddev driver version is 1.0.4
```

**Comment by whalesalad** [comment]
Just adding some additional debug info here:

```
 ddcutil detect
Invalid display
   I2C bus:  /dev/i2c-12
   DRM connector:           card0-DP-3
   EDID synopsis:
      Mfg id:               APP - Apple Computer Inc
      Model:                StudioDisplay
      Product code:         44602  (0xae3a)
      Serial number:
      Binary serial number: 2559404520 (0x988d69e8)
      Manufacture year:     2022,  Week: 7
   DDC communication failed
```

didn't expect this to work but tried anyway:

```
sudo asdcontrol --detect "/dev/i2c-12"
ASDControl 0.4 -- Apple Studio Display Brightness Control
Copyright (c) 2023-2024 Nicholas K. Dionysopoulos

hiddev driver version is 0.0.0
^C
```

The command just hangs and never completes.

Will keep poking around to see if there is going to be any way to leverage this as-is over the DisplayPort bus or not.

**Comment by whalesalad** [comment]
Also curious if anyone who is using this can share their hardware setup? Are you using a graphics card that has a usb-c output port? 

I have a Thunderbolt add-in card that connects to the GPU and then the display connects to the add-in card, but it never seems to work for me.

**Comment by nikosdion** [comment]
You cannot use this software, or control the monitor in general, over DisplayPort. You need to connect directly over a USB-C cable. The reason is that this monitor acts as both a monitor (DisplayPort signal over a USB-C physical connection) and as a USB 3.2 hub. The control happens over USB, not over DisplayPort (DDC). That's the whole reason I had to fork `acdcontrol` instead of using, say, DDC Control.

Regarding my setup, I have tried it with a laptop, over USB-C, using integrated Intel graphics. I didn't bother trying it with a desktop since the discrete graphics card of my machine only outputs DisplayPort and HDMI, it doesn't do USB-C. It's a very limiting monitor if you don't have a Mac, so I ended up giving it to my wife who's using a Mac, while I switched back to a Dough Spectrum 27" which is just as high quality, same resolution, has better refresh rate (144Hz to Apple's 60), and I can connect to it over USB-C, DisplayPort, and dual HDMI while costing just over a third of the Studio Display's price. It doesn't have a webcam, but that was trivially fixed :)

**Comment by whalesalad** [comment]
@nikosdion thanks for the detailed response!

**Comment by nikosdion** [comment]
You're welcome!
